### ISSUE TITLE
گزارش تبلیغات

### ISSUE THREAD

**Issue by Chamrosh** [SlashArash/adblockfa#12]
سلام

تو این چندتا سایت بنرهای تبلیغاتی زیادی موجوده، حذف نشده

[techna](https://techna.news/)
[itresan](https://itresan.com)
[farnet](https://farnet.io/)

 تشکر بابت وقتی که میذارید

**Comment by SlashArash** [comment]
سلام
@Chamrosh خیلی لطف کردی که این سایت‌ها رو معرفی کردی.
سعی کردم تبلیغاتشون رو فیلتر کنم و الان منتشر شده. به زودی می‌تونی ببینی. اگه مشکلی بود بهم باز اطلاع بده لطفاً.

**Comment by MasterKia** [comment]
درود @Chamrosh 
من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست PersianBlocker رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.

فیلتر های این لیست (Adblock Farsi) رو به مرور به اون لیست اضافه خواهم کرد تا پوشش دهی و کاربرد لیست بره.

**Comment by MasterKia** [comment]
آدرس لیست رو یادم رفت بنویسم:
https://github.com/MasterKia/PersianBlocker
