### ISSUE TITLE
گزارش تبلیغات

### ISSUE THREAD

**Issue by Chamrosh** [SlashArash/adblockfa#13]
سلام
وقتتون بخیر

[دیجیاتو](https://digiato.com/)
`||click.digiato.com/
`

[سافت۹۸](https://soft98.ir/)
`soft98.ir##.a7d7x`
`soft98.ir##.a7d7x-image`

تشکر بابت تلاشتون

**Comment by SlashArash** [comment]
سلام. ممنون از لطفت. عذر می‌خوام به خاطر تاخیر ولی این فیلترها و یکی دوتا فیلتر دیگه اضافه شدند.
