### ISSUE TITLE
گزارش تبلیغات

### ISSUE THREAD

**Issue by chromer030** [SlashArash/adblockfa#14]
با سلام و وقت به خیر
سایت [بیتوته](https://www.beytoote.com/) به لحاظ حجم تبلیغات فاجعه است ، این فیلترها تقریبا همه تبلیغاتش رو میگیرن   

```
! 2021-05-29 https://www.beytoote.com
||storage.beytoote.com/images/adsbeytoote/img/$popup
||storage.beytoote.com/images/adsbeytoote/$popup
||storage.beytoote.com/images/adsbeytoote/img/$image
||storage.beytoote.com/images/adsbeytoote/$image
||storage.beytoote.com/images/adsbeytoote/img/*.gif$image
||storage.beytoote.com/images/adsbeytoote/*.gif$image
||storage.beytoote.com/images/adsbeytoote/*.png$image
||storage.beytoote.com/images/adsbeytoote/*.jpg$image
||storage.beytoote.com/images/adsbeytoote/img/*.gif$popup
||storage.beytoote.com/images/adsbeytoote/*.gif$popup
||storage.beytoote.com/images/adsbeytoote/*.gif
||storage.beytoote.com/images/adsbeytoote/lazy-desk.js
||storage.beytoote.com/images/adsbeytoote/lazy-mobile.js
||www.beytoote.com/ads/socket.io.js
www.beytoote.com###esc1
www.beytoote.com##.pc_top_bil.countclick.count
```

برای سایت [های دکتر](https://hidoctor.ir) 
‍‍‍```
||hidoctor.ir^$third-party
```

**Comment by SlashArash** [comment]
سلام سلام
ببخشید دیر جواب می‌دم یکم تنبلی کردم. این که ایشو باز کردی و این قدر اطلاعات هم دادی خیلی با ارزشه. مرسی.
بیتوته رو یکم خلاصه‌تر اضافه کردم و تمیز شد. در مورد «های دکتر» به نظرم اگه فقط سایت‌هایی که کارشون تبلیغات هست رو به این صورت فیلتر کنیم خیلی بهتره. البته در گذشته خودم این کار رو می‌کردم چون خیلی تبلیغات سایت‌های مثل دیجیکالا یا دیگران زیاد بود. اگه «های دکتر» هم خیلی زیاده می‌شه اضافه کرد ولی اگه یکی دو مورد هست به نظرم ارزش نداره. باز هم ممنونم و اگه نظری داری همین ایشو رو باز کن مرسی.

**Comment by chromer030** [comment]
بسیار ممنونم از بررسی و اضافه کردن فیلتر

**Comment by MasterKia** [comment]
درود @chromer030 

من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.

فیلتر های این لیست (Adblock Farsi) رو به مرور به اون لیست اضافه خواهم کرد تا پوشش دهی و کاربرد لیست بالا بره.

**Comment by chromer030** [comment]
@MasterKia 
درود فراوان.
خیلی خیلی عالی ، از طرف خودم از زحماتت تشکر میکنم ، یه لیست به این جامعی مدت هاست که نیازش حس میشه.
سعی میکنم تبلیغات فیلتر نشده ای که میبینم رو [گزارش کنم.](https://github.com/MasterKia/PersianBlocker)

**Comment by MasterKia** [comment]
تلاش میکنم به دوستان دیگه ای که قبلاً در Issue های این ریپو و ریپوی [Adblock-Iran](https://github.com/farrokhi/adblock-iran) فعّالیت داشتن هم این لیست جدید رو اطلاع بدم تا با خبر بشن و اگه خواستن مشارکت کنن.

خیلی از کاربر های پارسی زبان uBlock Origin رو نصب دارن اما متاسفانه ممکنه از حضور یک همچین لیستی داخلش بی خبر باشن و فعّالش نکنن؛ برای همین خیلی مهمه که اطلاع رسانی انجام بشه و ازین لیست با خبر بشن.
