### ISSUE TITLE
May you please add these domains to ads list

### ISSUE THREAD

**Issue by 0xRustlang** [SlashArash/adblockfa#18]
سلام
لطفا درصورت امکان این دامنه ها رو هم توی لیست تبلیغات تون قرار بدین

در آخر خیلی ممنون و
موفق و پاینده باشید

netbina.com
netbina.net

appsharj.com
api.appsharj.com

api.sanjagh.com
sanjagh.com
sanjagh.net

fastclick.click
fastclick.co

kaprila.com
landyab.com
tavoos.net
iranwebads.com
merita.ir
mihanclick.info
networksara.com
nextads.ir
popland.info
utop.ir
vatanclick.ir
weclick.ir
ad2ad.ir
adnegah.net
adsima.net
adpulse.ir
adtube.ir
clickyab.com
iprank.ir
impressions.ir
ipopup.ir
ipsell.ir
popupads.ir
irclick.net
persianrank.ir

persianstat.com
persianstat.ir

metrix.ir
analytics.metrix.ir

api.tapsell.ir
najva.com

adad.ir
s.adad.ir

با تشکر فراوان

**Comment by SlashArash** [comment]
@rustforfuture 
سعی می‌کنم که امروز یکی یکی بررسی کنم و اضافه‌شون کنم. خیلی ممنونم از لطفت

**Comment by 0xRustlang** [comment]
خیلی ممنون
لطف کردین
