### ISSUE TITLE
May you please create a simple url list for dns based blockers?

### ISSUE THREAD

**Issue by 0xRustlang** [SlashArash/adblockfa#19]
سلام
توی لیستتون خیلی سایتایی هست که صرفا کارشون تبلیغات کلیکی هست

امکانش هست براتون لطف کنین که اون سایتایی که فقط تبلیغات کامل هستن (اد نتورک هستن) رو توی یه لیست جدا فقط آدرسشون رو مثل این لیست درست کنین؟

https://github.com/farrokhi/adblock-iran/blob/master/pihole.txt

خیلی ممنون میشم و خیلی فوق العاده میشه همچین چیزی

**Comment by SlashArash** [comment]
سلام. من متوجهم که شاید لازم بشه که چنین فهرستی هم داشته باشیم ولی به‌روزرسانی و نگهداری از یه فایل دیگه برام خیلی مقدور نیست مگر اینکه مزیت مهمی داشته باشه. این ایشو رو می‌بندم ولی در ذهنم هست که اگه وقت اضافه داشتم حتماً‌ این کار رو بکنم.

**Comment by 0xRustlang** [comment]
خیلی ممنون
واقعا فوق العاده میشه
لطف میکنید
