### ISSUE TITLE
"ads/images" rule is making false positives

### ISSUE THREAD

**Issue by samehraban** [SlashArash/adblockfa#3]
The rule "ads/images" is also being applied to "uploads/images". 
Maybe change to "/ads/images"?

![selection_004](https://user-images.githubusercontent.com/7755954/32600879-404f71ea-c556-11e7-8bad-335d2b99b2aa.png)

**Comment by SlashArash** [comment]
sure, thanks for your report. I'll fix it in the next release

**Comment by MasterKia** [comment]
درود @samehraban 

من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.

فیلتر های این لیست (Adblock Farsi) رو به مرور به اون لیست اضافه خواهم کرد تا پوشش دهی و کاربرد لیست بره.
