### ISSUE TITLE
تبلیغات کاپریلا

### ISSUE THREAD

**Issue by amirlilg** [SlashArash/adblockfa#5]
سلام. 
تبلیغات سایت 
http://kaprila.com
در سایت ها بلاک نمی شود.  مثل سایت p30download.com
اگه میتونین رسیدگی کنید

**Comment by worldmohammad** [comment]
سلام چهار سال پیش قبل پیدا شدن این لیست ها یه لیست برای استفاده شخصی نوشته بودم که الان نسخه جدیدشو آماده کردم تو این نسخه تبلیغات تمام سیستم تبلیغاتی فارسی زبان رو کامل حذف میکنه
http://digifilestore.ir/ad-blocking-filter-on-persian-sites-with-adgaurd-plugin/

**Comment by SMed79** [comment]
@amirlilg add these filters
```
||kaprila.com^$third-party
||p30download.com/agahi/files/
||p30download.com/tabliq/banner/
```

**Comment by SlashArash** [comment]
@amirlilg سلام
تبلیغات کاپریلا فیلتر شده ولی گاهی از فیلترها عبور می‌کنه که نمی‌دونم علتش چیه. کافیه یه بار صفحه رو تازه‌سازی یا ریفرش کنید.

@SMed79 ممنون از لطفت ولی این فیلترها توی لیست موجوده.
اولین فیلتر که حتماً هست ولی دومی و سومی به صورت عمومی‌تر نوشته شده.

**Comment by MasterKia** [comment]
درود @amirlilg
من همه فیلتر های لیست Adblock-Iran رو بازنویسی کردم و لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) رو به وجود آوردم.
امروز لیست PersianBlocker به لیست های پیشفرض uBlock Origin [افزوده](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) شد.

فیلتر های این لیست (Adblock Farsi) رو به مرور به اون لیست اضافه خواهم کرد تا پوشش دهی و کاربرد لیست بره.
